### ISSUE TITLE
OSError: No suitable library found for xls

### ISSUE THREAD

**Issue by kimardenmiller** [pyexcel/pyexcel-xls#12]
With the sample code:

from pyexcel_xls import save_data
from collections import OrderedDict
data = OrderedDict() # from collections import OrderedDict
data.update({"Sheet 1": [[1, 2, 3], [4, 5, 6]]})
data.update({"Sheet 2": [["row 1", "row 2", "row 3"]]})
save_data("kim_file.xls", data)

I get:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-39-6cbdcd5be247> in <module>()
      5 data.update({"Sheet 1": [[1, 2, 3], [4, 5, 6]]})
      6 data.update({"Sheet 2": [["row 1", "row 2", "row 3"]]})
----> 7 save_data("kim_file.xls", data)

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_xls/__init__.py in save_data(afile, data, file_type, **keywords)
     29     if isstream(afile) and file_type is None:
     30         file_type = _FILE_TYPE
---> 31     write_data(afile, data, file_type=file_type, **keywords)

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/io.py in store_data(afile, data, file_type, **keywords)
     88             file_name=afile,
     89             file_type=file_type,
---> 90             **keywords)
     91     writer.write(data)
     92     writer.close()

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/io.py in get_writer_new(file_name, file_stream, file_type, library, **keywords)
    145         file_type_given = False
    146 
--> 147     writer = RWManager.create_writer(file_type, library)
    148     if file_name:
    149         if file_type_given:

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/manager.py in create_writer(file_type, library)
    100     def create_writer(file_type, library=None):
    101         writer = RWManager._get_a_handler(
--> 102             RWManager.writer_factories, file_type, library)
    103         if writer is None:
    104             resolve_missing_writers(file_type)

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/manager.py in _get_a_handler(factories, file_type, library)
     87             return handler
     88 
---> 89         raise IOError("No suitable library found for %s" % file_type)
     90 
     91     @staticmethod

OSError: No suitable library found for xls

Same as a Plugin:

import pyexcel as pe
content = "1,2,3\n3,4,5"
sheet = pe.Sheet(content)
sheet.save_as("pima.xls")

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-41-df25d9a5ab15> in <module>()
      2 content = "1,2,3\n3,4,5"
      3 sheet = pe.Sheet(content)
----> 4 sheet.save_as("pima.xls")

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel/sheets/sheet.py in save_as(self, filename, **keywords)
    452         """
    453         return save_sheet(self, file_name=filename,
--> 454                           **keywords)
    455 
    456     def save_to_memory(self, file_type, stream=None, **keywords):

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel/sources/__init__.py in save_sheet(sheet, **keywords)
     36     """
     37     source = factory.get_writable_source(**keywords)
---> 38     return _save_any(source, sheet)
     39 
     40 

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel/sources/__init__.py in _save_any(source, instance)
     48 
     49 def _save_any(source, instance):
---> 50     source.write_data(instance)
     51     if hasattr(source, 'content'):
     52         _try_put_file_read_pointer_to_its_begining(source.content)

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel/sources/file_source_output.py in write_data(self, sheet)
     45     def write_data(self, sheet):
     46         self.renderer.render_sheet_to_file(self.file_name,
---> 47                                            sheet, **self.keywords)
     48 
     49 

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel/renderers/_excel.py in render_sheet_to_file(self, file_name, sheet, **keywords)
     19             sheet_name = sheet.name
     20         data = {sheet_name: sheet.to_array()}
---> 21         save_data(file_name, data, **keywords)
     22 
     23     def render_book_to_file(self, file_name, book, **keywords):

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/io.py in save_data(afile, data, file_type, **keywords)
     68                file_type=file_type,
     69                single_sheet_in_book=single_sheet_in_book,
---> 70                **keywords)
     71 
     72 

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/io.py in store_data(afile, data, file_type, **keywords)
     88             file_name=afile,
     89             file_type=file_type,
---> 90             **keywords)
     91     writer.write(data)
     92     writer.close()

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/io.py in get_writer_new(file_name, file_stream, file_type, library, **keywords)
    145         file_type_given = False
    146 
--> 147     writer = RWManager.create_writer(file_type, library)
    148     if file_name:
    149         if file_type_given:

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/manager.py in create_writer(file_type, library)
    100     def create_writer(file_type, library=None):
    101         writer = RWManager._get_a_handler(
--> 102             RWManager.writer_factories, file_type, library)
    103         if writer is None:
    104             resolve_missing_writers(file_type)

/Users/kimardenmiller/anaconda/envs/tensorflow/lib/python3.5/site-packages/pyexcel_io/manager.py in _get_a_handler(factories, file_type, library)
     87             return handler
     88 
---> 89         raise IOError("No suitable library found for %s" % file_type)
     90 
     91     @staticmethod

OSError: No suitable library found for xls

**Comment by chfw** [comment]
Sorry for the late reply. Please check using 'pip freeze' and see if pyexcel-xls is installed in your environment.
