### ISSUE TITLE
sdist upload missing in latest PyPI release

### ISSUE THREAD

**Issue by ashkulz** [pyexcel/pyexcel-xls#19]
The latest PyPI release (`0.3.3`) just has a wheel, but not a `sdist upload`. I can understand that it is convenient to have a wheel upload, but this breaks some packaging workflows (I build internal debian packages which assume that the source will be present on PyPI). Please consider including it for the current and future releases as done earlier e.g. see [0.3.1](https://pypi.python.org/pypi/pyexcel-xls/0.3.1) which just has the source.

**Comment by chfw** [comment]
Oh, I am sorry that I was ignorant on the difference between sdist and bdist. I started upload wheels instead of tar.gz. I thought both are equally OK so I did not upload tar.gz file. I will upload tar.gz file now to keep you workflow.

**Comment by chfw** [comment]
uploaded. please check it out.

**Comment by ashkulz** [comment]
Thanks a lot, works now :+1:
