### ISSUE TITLE
How to detect merged cell in .xls

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel-xls#25]
I have a similar situation as in this SO question about reading merged cell values and have it apply to subsequent rows in .xls files https://stackoverflow.com/a/30753988/80353

I wonder if there's a way to do it using pyexcel-xls API **without resorting to the answer** given in the SO question?

**Comment by chfw** [comment]
Pyexcel tried to read the data only without concerning styles. So it won't be possible with existing apis. Could you please share the link to the SO answer? 

And for next version , we have plans for writing data with some styles.

**Comment by simkimsia** [comment]
Added. Coolness. Thanks

**Comment by chfw** [comment]
Thanks for your pledge on Patreon. I will prioritise this issue and see what I can do.

**Comment by chfw** [comment]
New flag: `detect_merged_cells` allows you to spread the same value among all merged cells. But be aware that this may slow down its reading performance.

**Comment by simkimsia** [comment]
Thanks for this @chfw. The merged cells gave me so much issues that i eventually decided it was easier to simply split the merged cells and then fill them up with the preceding steps instead.
