### ISSUE TITLE
Installation - 

### ISSUE THREAD

**Issue by KevinSe** [pyexcel/pyexcel-xls#3]
Hello,

First of all, thank you for your work.

I'm new to this library. At installation on a Mac OS 10.10.5, the command:

`$ python setup.py install`

throws:

```
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    extras_require=extras,
NameError: name 'extras' is not defined
```

Do you know how to solve this problem / what may have caused it?
Thank you in advance,
- K.

**Comment by chfw** [comment]
Yes, I do. It occured in my recent documentation refactoring. Will fix it in a minute.
