### ISSUE TITLE
Incompatibility with pyexcel-io v0.5.12

### ISSUE THREAD

**Issue by ShaheedHaque** [pyexcel/pyexcel-xls#30]
It seems that pyexcel-io v0.5.12, in 43a5a56227128fbdcc39b6a2932571aac0f1adbd got rid of io.store_data(). Unfortunately, that entry point is imported by pyexcel-xls (and pyexcel-xlsx). A patch like this is needed to allow the import to work (but I'm not 100% sure if there is any more to it than this):

```
$ diff /usr/local/lib/python3.6/dist-packages/pyexcel_xls/__init__.py.saved /usr/local/lib/python3.6/dist-packages/pyexcel_xls/__init__.py
14c14
< from pyexcel_io.io import get_data as read_data, isstream, store_data as write_data
---
> from pyexcel_io.io import get_data as read_data, isstream, save_data as write_data
```

**Comment by ShaheedHaque** [comment]
I also think the same issue may affect pyexcel-ods and pyexcel-ods3.

I guess an alternative hack would be to add "store_data = save_data" into pyexcel-io to restore backwards compatibility?

**Comment by chfw** [comment]
Yep I remember it now. Will provide a fix.

**Comment by chfw** [comment]
Pulled it back for now

**Comment by ShaheedHaque** [comment]
Actually, the "simple fix" gets past the import problem but does not work:

`TypeError: save_data() got multiple values for keyword argument 'single_sheet_in_book'`

**Comment by chfw** [comment]
Dev branch has the fix already. I forgot such an incompatibility. 

I need to rollout all plugins at the same time.

**Comment by chfw** [comment]
@ShaheedHaque , the implementation has been changed. It is a late realization that private function(store_data) shall not be used in public way.

My original intention was to rolling out the code refactoring togather with version 0.6.0. But when time passes by, I forgot my intent and started to roll out the code refactoring in 0.5.x branch.

My withdrawal of the 0.5.12 is to reserve the code refactoring to 0.6.0 so that other break changes would go togather in 0.6.0 and in one go, it would be worthy of your time and others' to update it.

**Comment by ShaheedHaque** [comment]
Understood: these things happen, especially when we are not working on such projects full time. Thanks for your quick feedback. I've pinned myself to 0.5.11 for now.

**Comment by chfw** [comment]
this has been fixed by later versions. 

in v0.6.0, I hope to update all plugins at once so that 0.5.x will needs update to 0.6.x. But all plugins and pyexcel-io on 0.6.x will work without problems.

**Comment by ShaheedHaque** [comment]
Hmm, is there a fix on 0.5.x? Can you point to the fix commit please?

**Comment by chfw** [comment]
Not really a fix but avoid the the problem by later fixes. You should be OK pinning to 0.5.11

**Comment by ShaheedHaque** [comment]
pyexcel-ods 0.5.6 seems to require 0.5.16. Is it OK to remove the pin-to-0.5.11?

**Comment by chfw** [comment]
Yep it is safe.I am not going to introduce the api break in 0.5.x line.

**Comment by ShaheedHaque** [comment]
Thanks!
