### ISSUE TITLE
Tests missing from the archive

### ISSUE THREAD

**Issue by jtojnar** [pyexcel/pyexcel-xls#35]
Looks like the tests are still missing in https://files.pythonhosted.org/packages/source/p/pyexcel-xls/pyexcel-xls-0.5.8.tar.gz.

See also https://github.com/pyexcel/pyexcel-io/issues/60

**Comment by chfw** [comment]
MANIFEST.in will include tests but the change was made 8 months ago. But v0.5.8 was released in 2018 and ever since, I have not updated the package. 

Do you need tests for something?

**Comment by jtojnar** [comment]
Just like https://github.com/pyexcel/pyexcel-io/issues/60, I am packaging pyexcel for a linux distro (https://github.com/NixOS/nixpkgs/pull/96483) and would like to run the tests to increase our certainty things are okay.

**Comment by chfw** [comment]
sure and thanks for spreading the love. I will make one release with tests.

**Comment by chfw** [comment]
Tests folder seems to be there?

https://github.com/pyexcel/pyexcel-xls/archive/0.5.8.tar.gz

```
x pyexcel-xls-0.5.8/setup.cfg
x pyexcel-xls-0.5.8/setup.py
x pyexcel-xls-0.5.8/test.bat
x pyexcel-xls-0.5.8/test.sh
x pyexcel-xls-0.5.8/tests/
x pyexcel-xls-0.5.8/tests/_compact.py
x pyexcel-xls-0.5.8/tests/base.py
x pyexcel-xls-0.5.8/tests/fixtures/
x pyexcel-xls-0.5.8/tests/fixtures/complex-merged-cells-sheet.xls
x pyexcel-xls-0.5.8/tests/fixtures/complex_hidden_sheets.xls
x pyexcel-xls-0.5.8/tests/fixtures/date_field.xls
x pyexcel-xls-0.5.8/tests/fixtures/file_with_an_empty_sheet.xls
x pyexcel-xls-0.5.8/tests/fixtures/hidden.xls
x pyexcel-xls-0.5.8/tests/fixtures/hidden_sheets.xls
x pyexcel-xls-0.5.8/tests/fixtures/merged-cell-sheet.xls
x pyexcel-xls-0.5.8/tests/fixtures/merged-sheet-exploration.xls
x pyexcel-xls-0.5.8/tests/fixtures/pyexcel_issue_151.xlsx
x pyexcel-xls-0.5.8/tests/fixtures/test-date-format.xls
x pyexcel-xls-0.5.8/tests/requirements.txt
x pyexcel-xls-0.5.8/tests/requirements3.txt
x pyexcel-xls-0.5.8/tests/test_bug_fixes.py
x pyexcel-xls-0.5.8/tests/test_filter.py
x pyexcel-xls-0.5.8/tests/test_formatters.py
x pyexcel-xls-0.5.8/tests/test_hidden.py
x pyexcel-xls-0.5.8/tests/test_merged_cells.py
x pyexcel-xls-0.5.8/tests/test_multiple_sheets.py
x pyexcel-xls-0.5.8/tests/test_stringio.py
x pyexcel-xls-0.5.8/tests/test_writer.py
```

**Comment by chfw** [comment]
but the file you mentioned, indeed, does not have the tests. I will cook up v0.5.9 from master branch

**Comment by jtojnar** [comment]
https://github.com/pyexcel/pyexcel-xls/archive/0.5.8.tar.gz is just a snapshot of the Git repo, distros are typically getting python packages from PyPI https://pypi.org/project/pyexcel-xls/#files

**Comment by chfw** [comment]
Do you still need 0.5.9 with tests?

**Comment by jtojnar** [comment]
It would be very useful but we can also package it without tests until you are ready to release a new version.

**Comment by chfw** [comment]
The next release will be 0.6.0 if it is not urgent.

Pyexcel-io v0.6.0 is under development so soon all its plugins will get an upgrade to 0.6.0 line.

**Comment by chfw** [comment]
a maintenance version is produced here: https://pypi.org/project/pyexcel-xls/0.5.9/

**Comment by jtojnar** [comment]
Thank you, updated: https://github.com/NixOS/nixpkgs/commit/5cfd8275a64da9fd38d061441dbce74ccb5c1ddd
