### ISSUE TITLE
0.6.0 removed from pypi

### ISSUE THREAD

**Issue by oppianmatt** [pyexcel/pyexcel-xls#40]
Our builds started failing when it couldn't find 0.6.0

I think it was removed by accident yesterday when the new version 0.6.1 was added

![image](https://user-images.githubusercontent.com/48596/96866493-49f45800-1463-11eb-94dd-e3f99454aba6.png)

https://pypi.org/project/pyexcel-xls/#history

**Comment by chfw** [comment]
I am sorry about that. I have removed 0.6.0 from pypi because it allows the installation on python 2. 

Next time I Must not remove a version at will.

**Comment by chfw** [comment]
Please update to use 0.6.1. I should have realized my community will depend on it as it was released for some time.
